### ISSUE TITLE
Termux Error

### ISSUE THREAD

**Issue by NoXLaw** [surfcodes/surf#16]
**Describe the bug**
I cant to run surf cli on termux app, and it show this error'
``` bash
surf .
/data/data/com.termux/files/usr/bin/surf: 3: [: .: unexpected operator
/data/data/com.termux/files/usr/bin/surf: 3: [: .: unexpected operator
/data/data/com.termux/files/usr/bin/surf: 3: [: .: unexpected operator
/data/data/com.termux/files/usr/bin/surf: 23: Bad substitution
```

**Screenshots**
![Screenshot_20210216-143143](https://user-images.githubusercontent.com/35652825/108031596-b6731280-7063-11eb-9942-860c0d18f33e.png)

**Comment by GwonHeeJun** [comment]
Is this IPhone Application?

**Comment by lawbyte** [comment]
> Is this IPhone Application?

No.. this on android

**Comment by GwonHeeJun** [comment]
> > Is this IPhone Application?
> 
> No.. this on android

Umm... Now, We are support Notebook & Desktop.

**Comment by kylekanglin** [comment]
@GwonHeeJun could you pls reopen and check this issue? Cuz i encountered the same issue on my laptop (linux).
