### ISSUE TITLE
Relationship between surf's official chrome extension and Darkempire78/Github1s-Extension

### ISSUE THREAD

**Issue by shunia** [surfcodes/surf#27]
Sorry if I miss related them but by checking out the source code I do found they looks really alike:

Official chrome extension:
https://github.com/surfcodes/surf/blob/main/chrome-extension/surf.github.js

Darkempire78/Github1s-Extension:
https://github.com/Darkempire78/Github1s-Extension/blob/main/content.js

And I don't understand licenses but I guess it's fine to redistribute the source code from Darkempire78/Github1s-Extension by the [license (GPL v3.0)](https://github.com/Darkempire78/Github1s-Extension/blob/main/LICENSE) but you should keep the `License and copyright notice` and with `Same license`?

**Comment by softmarshmallow** [comment]
https://github.com/surfcodes/surf/blob/main/chrome-extension/surf.gist.github.js
