### ISSUE TITLE
my-cool-package


### ISSUE THREAD

**Issue by sluckbla197** [surfcodes/surf#31]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

All bugs linked me back to Github and a few other sites. My google accounts gets taken, and my phones screen and apps are over ruled by the copy-righted licenses on phone setup, google, and some other apps. Where I made no installation on any of them particular applications. Also I did ALOT of research over the passed 2 years since now I found out this chick I was dating is related or working for a company/organization and was collecting my information and pretending not too. I need a fellow on here too help me fight this so I can live cyber-free and peaceful. Thank you for your time!!!! 3-19-2021

**Comment by GwonHeeJun** [comment]
Opps...? What is this issue?

**Comment by GwonHeeJun** [comment]
Um... What is that issue?

**Comment by sluckbla197** [comment]
Hacked device

**Comment by sluckbla197** [comment]
[]()![Screenshot_20210216-233207.png](https://user-images.githubusercontent.com/79190321/108544797-f67d0400-72b4-11eb-8d0c-029850dd4d32.png)

**Comment by sluckbla197** [comment]
@JoseDeFreitas hacked me

**Comment by sluckbla197** [comment]
![Screenshot_20210217-003822.png](https://user-images.githubusercontent.com/79190321/108545098-57a4d780-72b5-11eb-9f28-d19a9ae8ef39.png)

**Comment by sluckbla197** [comment]
What can I do about this information regarding my interuption on my device?

**Comment by JoseDeFreitas** [comment]
Hello. Can you explain what is this? Why did you mention me? 🤔

**Comment by sluckbla197** [comment]
Suddenly shown up on my device

**Comment by JoseDeFreitas** [comment]
Sorry, you're confused. I don't know why you mentioned me, but the only thing I've done in this project is this pull request: #18 (where I fixed some typos in the README file).

**Comment by sluckbla197** [comment]
Thank you for the clarification.

**Comment by JoseDeFreitas** [comment]
It's all right, no problem 👍.

**Comment by sluckbla197** [comment]
Will do, thanks!
