### ISSUE TITLE
after I readed the readme twice time, I don't know how to use it. Someone can help me ?

### ISSUE THREAD

**Issue by tainzhi** [surfcodes/surf#38]
I searched vscode extension with `surf` or `githubsurf`, I couldn't get any supported one. After I readed the readme, I couldn't use it with vscoe. Could someone give me a hand?

**Comment by GwonHeeJun** [comment]
We don't have vscode extension packs right now.

We have Chrome extension

**Comment by tainzhi** [comment]
thanks for your help
